FROM node:22-alpine3.20 AS build

LABEL key="m.otieno205@gmail.com"

WORKDIR /client

COPY package*.json ./

RUN npm i && npm cache clean --force && rm -rf /tmp/*

COPY . .

RUN npm run build && npm prune --production

FROM node:22-alpine3.20

WORKDIR /client

ENV NODE_ENV=production

EXPOSE 3000

CMD [ "npm", "start"]

