services:

  #Builds the frontend Docker image and creates the frontend microservice
  client:
    image: motieno205/client-app:v1.5.0
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "3000:3000"
    depends_on: 
      - backend
    networks:
      - app-network

  #Builds the backend Docker image and creates the backend microservice
  backend:
    image: motieno205/backend:v1.2.1
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    depends_on: 
      - mongodb
    networks:
      - app-network
    environment:
      - MONGODB_URI=mongodb://admin:supersecret@mongodb:27017/yolomy?authSource=admin


  #Creates the database microservice
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: supersecret

    networks:
      - app-network
      
    volumes:
        - mongo-volume:/data/db
   

#Creates the network infrastructure necessary for the containers to communicate with each other
networks:
  app-network:
    name: app-network
    driver: bridge
    
    
volumes:
  mongo-volume:
    driver: local