apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app-deployment
  labels:
    app: backend-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend-app
        image: motieno205/backend:v1.2.1
        ports:
        - containerPort: 5000
        env:
        - name: MONGODB_URL
          value: "mongodb://mongo:27017/yolomy" 
        


---
apiVersion: v1
kind: Service
metadata:
  name: backend-app-service
spec:
  selector:
    app: backend-app
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP

