apiVersion: v1
kind: Secret
metadata: 
  name: mongodb-secret
  immutable: false
type: Opaque
data:
  username: YWRtaW4=  # Base64-encoded value of "admin" === on terminal echo -n "admin" | base64 YWRtaW4=
  password: c3VwZXJzZWNyZXQ=  # Base64-encoded value of "supersecret" === on terminal echo echo -n "supersecret" | base64

